name: TF Actions Workflow

on:
    pull_request:
      branches:
        - main
    push:
      branches:
        - main


env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

jobs:
  terraform_validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Validate
        run: terraform validate


  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Go to Working Directory
        run: cd ./iac/environments/prod

      - name: Init
        run: terraform init -backend-config="config.s3.tfbackend"

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply
        if: github.event_name == 'push'
        run: terraform apply -var-file="terraform.tfvars" -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
